# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7239ee5377ff8f67911f9fc60081457fbcd9769866ce9bf20d5483b85c9c3caa264f779585c046fe75ece93cf619075ca72bf261bcc41177a3d51f7b2ccdcddf

test:
  secret_key_base: ebb9bcd41ad43a85a3b4cd7f2e78cb516bb1150aee3245ba68e98d5f899947aee26637d1c863098c7f13f2315d7201267b432b3910a6a138911d8297026140a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
